Fix Docker caching issues while building container images
From the Docker best practices:
```
Always combine RUN apt-get update with apt-get install in the same RUN
statement. Using apt-get update alone in a RUN statement causes
caching issues and subsequent apt-get install instructions to fail.
```
https://docs.docker.com/build/building/best-practices/

That trick allows to fix the following error:
```
14.12 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-14-cross/libstdc%2b%2b6-ppc64el-cross_14.2.0-4ubuntu2%7e24.04cross1_all.deb  404  Not Found [IP: 104.20.28.246 80]
14.12 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-14-cross/libubsan1-ppc64el-cross_14.2.0-4ubuntu2%7e24.04cross1_all.deb  404  Not Found [IP: 104.20.28.246 80]
14.12 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-14-cross/libquadmath0-ppc64el-cross_14.2.0-4ubuntu2%7e24.04cross1_all.deb  404  Not Found [IP: 104.20.28.246 80]
14.12 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
Dockerfile:13
--------------------
  12 |     ARG GCC_VERSION
  13 | >>> RUN set -ex; \
  14 | >>>     if [ "$GCC_VERSION" ]; then \
  15 | >>>       apt-get install -y -q gcc-${GCC_VERSION} g++-${GCC_VERSION} gcc-${GCC_VERSION}-plugin-dev \
  16 | >>>         gcc-${GCC_VERSION}-aarch64-linux-gnu g++-${GCC_VERSION}-aarch64-linux-gnu \
  17 | >>>         gcc-${GCC_VERSION}-arm-linux-gnueabi g++-${GCC_VERSION}-arm-linux-gnueabi \
  18 | >>>         gcc-${GCC_VERSION}-powerpc-linux-gnu g++-${GCC_VERSION}-powerpc-linux-gnu \
  19 | >>>         gcc-${GCC_VERSION}-powerpc64le-linux-gnu g++-${GCC_VERSION}-powerpc64le-linux-gnu; \
  20 | >>>       if [ "$GCC_VERSION" != "4.9" ]; then \
  21 | >>>         apt-get install -y -q gcc-${GCC_VERSION}-powerpc64-linux-gnu g++-${GCC_VERSION}-powerpc64-linux-gnu; \
  22 | >>>         apt-get install -y -q gcc-${GCC_VERSION}-plugin-dev-aarch64-linux-gnu \
  23 | >>>           gcc-${GCC_VERSION}-plugin-dev-arm-linux-gnueabi \
  24 | >>>           gcc-${GCC_VERSION}-plugin-dev-powerpc-linux-gnu \
  25 | >>>           gcc-${GCC_VERSION}-plugin-dev-powerpc64le-linux-gnu \
  26 | >>>           gcc-${GCC_VERSION}-plugin-dev-powerpc64-linux-gnu; \
  27 | >>>       fi; \
  28 | >>>       if [ "$GCC_VERSION" != "4.9" ] && [ "$GCC_VERSION" != "5" ] && [ "$GCC_VERSION" != "6" ]; then \
  29 | >>>         apt-get install -y -q gcc-${GCC_VERSION}-riscv64-linux-gnu g++-${GCC_VERSION}-riscv64-linux-gnu gcc-${GCC_VERSION}-plugin-dev-riscv64-linux-gnu; \
  30 | >>>       fi; \
  31 | >>>       update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_VERSION} 100; \
  32 | >>>       update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC_VERSION} 100; \
  33 | >>>       update-alternatives --install /usr/bin/aarch64-linux-gnu-gcc aarch64-linux-gnu-gcc /usr/bin/aarch64-linux-gnu-gcc-${GCC_VERSION} 100; \
  34 | >>>       update-alternatives --install /usr/bin/aarch64-linux-gnu-g++ aarch64-linux-gnu-g++ /usr/bin/aarch64-linux-gnu-g++-${GCC_VERSION} 100; \
  35 | >>>       update-alternatives --install /usr/bin/arm-linux-gnueabi-gcc arm-linux-gnueabi-gcc /usr/bin/arm-linux-gnueabi-gcc-${GCC_VERSION} 100; \
  36 | >>>       update-alternatives --install /usr/bin/arm-linux-gnueabi-g++ arm-linux-gnueabi-g++ /usr/bin/arm-linux-gnueabi-g++-${GCC_VERSION} 100; \
  37 | >>>       update-alternatives --install /usr/bin/powerpc-linux-gnu-gcc powerpc-linux-gnu-gcc /usr/bin/powerpc-linux-gnu-gcc-${GCC_VERSION} 100; \
  38 | >>>       update-alternatives --install /usr/bin/powerpc-linux-gnu-g++ powerpc-linux-gnu-g++ /usr/bin/powerpc-linux-gnu-g++-${GCC_VERSION} 100; \
  39 | >>>       update-alternatives --install /usr/bin/powerpc64le-linux-gnu-gcc powerpc64le-linux-gnu-gcc /usr/bin/powerpc64le-linux-gnu-gcc-${GCC_VERSION} 100; \
  40 | >>>       update-alternatives --install /usr/bin/powerpc64le-linux-gnu-g++ powerpc64le-linux-gnu-g++ /usr/bin/powerpc64le-linux-gnu-g++-${GCC_VERSION} 100; \
  41 | >>>       if [ "$GCC_VERSION" != "4.9" ]; then \
  42 | >>>         update-alternatives --install /usr/bin/powerpc64-linux-gnu-gcc powerpc64-linux-gnu-gcc /usr/bin/powerpc64-linux-gnu-gcc-${GCC_VERSION} 100; \
  43 | >>>         update-alternatives --install /usr/bin/powerpc64-linux-gnu-g++ powerpc64-linux-gnu-g++ /usr/bin/powerpc64-linux-gnu-g++-${GCC_VERSION} 100; \
  44 | >>>       fi; \
  45 | >>>       if [ "$GCC_VERSION" != "4.9" ] && [ "$GCC_VERSION" != "5" ] && [ "$GCC_VERSION" != "6" ]; then \
  46 | >>>         update-alternatives --install /usr/bin/riscv64-linux-gnu-gcc riscv64-linux-gnu-gcc /usr/bin/riscv64-linux-gnu-gcc-${GCC_VERSION} 100; \
  47 | >>>         update-alternatives --install /usr/bin/riscv64-linux-gnu-g++ riscv64-linux-gnu-g++ /usr/bin/riscv64-linux-gnu-g++-${GCC_VERSION} 100; \
  48 | >>>       fi; \
  49 | >>>     fi
  50 |
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c set -ex;     if [ \"$GCC_VERSION\" ]; then       apt-get install -y -q gcc-${GCC_VERSION} g++-${GCC_VERSION} gcc-${GCC_VERSION}-plugin-dev         gcc-${GCC_VERSION}-aarch64-linux-gnu g++-${GCC_VERSION}-aarch64-linux-gnu         gcc-${GCC_VERSION}-arm-linux-gnueabi g++-${GCC_VERSION}-arm-linux-gnueabi         gcc-${GCC_VERSION}-powerpc-linux-gnu g++-${GCC_VERSION}-powerpc-linux-gnu         gcc-${GCC_VERSION}-powerpc64le-linux-gnu g++-${GCC_VERSION}-powerpc64le-linux-gnu;       if [ \"$GCC_VERSION\" != \"4.9\" ]; then         apt-get install -y -q gcc-${GCC_VERSION}-powerpc64-linux-gnu g++-${GCC_VERSION}-powerpc64-linux-gnu;         apt-get install -y -q gcc-${GCC_VERSION}-plugin-dev-aarch64-linux-gnu           gcc-${GCC_VERSION}-plugin-dev-arm-linux-gnueabi           gcc-${GCC_VERSION}-plugin-dev-powerpc-linux-gnu           gcc-${GCC_VERSION}-plugin-dev-powerpc64le-linux-gnu           gcc-${GCC_VERSION}-plugin-dev-powerpc64-linux-gnu;       fi;       if [ \"$GCC_VERSION\" != \"4.9\" ] && [ \"$GCC_VERSION\" != \"5\" ] && [ \"$GCC_VERSION\" != \"6\" ]; then         apt-get install -y -q gcc-${GCC_VERSION}-riscv64-linux-gnu g++-${GCC_VERSION}-riscv64-linux-gnu gcc-${GCC_VERSION}-plugin-dev-riscv64-linux-gnu;       fi;       update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_VERSION} 100;       update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC_VERSION} 100;       update-alternatives --install /usr/bin/aarch64-linux-gnu-gcc aarch64-linux-gnu-gcc /usr/bin/aarch64-linux-gnu-gcc-${GCC_VERSION} 100;       update-alternatives --install /usr/bin/aarch64-linux-gnu-g++ aarch64-linux-gnu-g++ /usr/bin/aarch64-linux-gnu-g++-${GCC_VERSION} 100;       update-alternatives --install /usr/bin/arm-linux-gnueabi-gcc arm-linux-gnueabi-gcc /usr/bin/arm-linux-gnueabi-gcc-${GCC_VERSION} 100;       update-alternatives --install /usr/bin/arm-linux-gnueabi-g++ arm-linux-gnueabi-g++ /usr/bin/arm-linux-gnueabi-g++-${GCC_VERSION} 100;       update-alternatives --install /usr/bin/powerpc-linux-gnu-gcc powerpc-linux-gnu-gcc /usr/bin/powerpc-linux-gnu-gcc-${GCC_VERSION} 100;       update-alternatives --install /usr/bin/powerpc-linux-gnu-g++ powerpc-linux-gnu-g++ /usr/bin/powerpc-linux-gnu-g++-${GCC_VERSION} 100;       update-alternatives --install /usr/bin/powerpc64le-linux-gnu-gcc powerpc64le-linux-gnu-gcc /usr/bin/powerpc64le-linux-gnu-gcc-${GCC_VERSION} 100;       update-alternatives --install /usr/bin/powerpc64le-linux-gnu-g++ powerpc64le-linux-gnu-g++ /usr/bin/powerpc64le-linux-gnu-g++-${GCC_VERSION} 100;       if [ \"$GCC_VERSION\" != \"4.9\" ]; then         update-alternatives --install /usr/bin/powerpc64-linux-gnu-gcc powerpc64-linux-gnu-gcc /usr/bin/powerpc64-linux-gnu-gcc-${GCC_VERSION} 100;         update-alternatives --install /usr/bin/powerpc64-linux-gnu-g++ powerpc64-linux-gnu-g++ /usr/bin/powerpc64-linux-gnu-g++-${GCC_VERSION} 100;       fi;       if [ \"$GCC_VERSION\" != \"4.9\" ] && [ \"$GCC_VERSION\" != \"5\" ] && [ \"$GCC_VERSION\" != \"6\" ]; then         update-alternatives --install /usr/bin/riscv64-linux-gnu-gcc riscv64-linux-gnu-gcc /usr/bin/riscv64-linux-gnu-gcc-${GCC_VERSION} 100;         update-alternatives --install /usr/bin/riscv64-linux-gnu-g++ riscv64-linux-gnu-g++ /usr/bin/riscv64-linux-gnu-g++-${GCC_VERSION} 100;       fi;     fi" did not complete successfully: exit code: 100
Traceback (most recent call last):
  File "/home/a13x/kernel-build-containers/./manage_images.py", line 265, in <module>
    main()
  File "/home/a13x/kernel-build-containers/./manage_images.py", line 254, in main
    build_images(args.build, images)
  File "/home/a13x/kernel-build-containers/./manage_images.py", line 157, in build_images
    c.build()
  File "/home/a13x/kernel-build-containers/./manage_images.py", line 89, in build
    subprocess.run(cmd, text=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'docker', 'buildx', 'build', '--build-arg', 'CLANG_VERSION=15', '--build-arg', 'GCC_VERSION=13', '--build-arg', 'UBUNTU_VERSION=24.04', '--build-arg', 'UNAME=a13x', '--build-arg', 'GNAME=a13x', '--build-arg', 'UID=1000', '--build-arg', 'GID=1000', '-t', 'kernel-build-container:clang-15', '-t', 'kernel-build-container:gcc-13', '.']' returned non-zero exit status 1.
```